"""
Generate random poly-alanine conformations as PDB files for visualizing an
intrinsically-disordered protein in PyMOL.

The chain is built residue-by-residue using the standard backbone dihedrals
(phi, psi, omega) as the only degrees of freedom. Bond lengths and bond
angles are fixed at canonical values; omega is fixed at 180 deg (trans
peptide). Each new atom is placed from three previous atoms via the
Natural Extension Reference Frame (NeRF) construction.

phi/psi pairs are sampled from a coarse coil-like distribution -- a mixture
of alpha_R, beta and PPII basins with Gaussian noise -- so the chain ends
up looking like a real disordered ensemble rather than a uniform-Ramachandran
random walk (which produces a lot of unphysical clashes).

Usage:
    python build_idp_conformations.py --n_aa 30 --n_conf 10 --seed 42
"""
import argparse
import os
import numpy as np


# Canonical bond lengths (Angstroms) and bond angles (degrees).
BL = {
    'N-CA':  1.458,
    'CA-C':  1.525,
    'C-N':   1.329,
    'C-O':   1.231,
    'CA-CB': 1.521,
}
BA = {
    'N-CA-C':  111.0,
    'CA-C-N':  116.2,
    'C-N-CA':  121.7,
    'CA-C-O':  120.5,
    'N-CA-CB': 110.4,
}


def nerf(a, b, c, length, angle_deg, dihedral_deg):
    """Place atom D from three reference atoms a, b, c.

    The returned point d satisfies:
        |c - d|              = length
        angle(b, c, d)       = angle_deg
        dihedral(a, b, c, d) = dihedral_deg
    """
    angle = np.radians(angle_deg)
    dihedral = np.radians(dihedral_deg)

    bc = c - b
    bc /= np.linalg.norm(bc)

    n = np.cross(b - a, bc)
    n /= np.linalg.norm(n)

    m = np.cross(n, bc)

    d_local = length * np.array([
        -np.cos(angle),
         np.cos(dihedral) * np.sin(angle),
         np.sin(dihedral) * np.sin(angle),
    ])

    R = np.column_stack([bc, m, n])
    return c + R @ d_local


def sample_phi_psi(mode='mixed'):
    """Return one (phi, psi) pair in degrees for a disordered residue."""
    if mode == 'uniform':
        return np.random.uniform(-180, 180), np.random.uniform(-180, 180)

    region = np.random.choice(['alpha_R', 'beta', 'PPII'],
                              p=[0.20, 0.35, 0.45])
    if region == 'alpha_R':
        return np.random.normal(-63, 8), np.random.normal(-43, 8)
    if region == 'beta':
        return np.random.normal(-130, 15), np.random.normal(135, 15)
    return np.random.normal(-75, 10), np.random.normal(145, 10)   # PPII


def build_chain(n_res, mode='mixed'):
    """Build a poly-alanine chain. Returns dict of (n_res, 3) coord arrays."""
    N  = np.zeros((n_res, 3))
    CA = np.zeros((n_res, 3))
    C  = np.zeros((n_res, 3))
    O  = np.zeros((n_res, 3))
    CB = np.zeros((n_res, 3))

    phis = np.zeros(n_res)
    psis = np.zeros(n_res)
    omegas = np.full(n_res, 180.0)
    for i in range(n_res):
        phis[i], psis[i] = sample_phi_psi(mode)

    # Anchor first three backbone atoms in a fixed initial frame.
    N[0]  = np.array([0.0, 0.0, 0.0])
    CA[0] = np.array([BL['N-CA'], 0.0, 0.0])
    th = np.radians(BA['N-CA-C'])
    C[0]  = CA[0] + BL['CA-C'] * np.array([-np.cos(th), np.sin(th), 0.0])

    # Walk the backbone using phi/psi/omega.
    for i in range(n_res - 1):
        N[i+1]  = nerf(N[i],  CA[i],  C[i],     BL['C-N'],  BA['CA-C-N'], psis[i])
        CA[i+1] = nerf(CA[i], C[i],   N[i+1],   BL['N-CA'], BA['C-N-CA'], omegas[i])
        C[i+1]  = nerf(C[i],  N[i+1], CA[i+1],  BL['CA-C'], BA['N-CA-C'], phis[i+1])

    # Carbonyl O: sits anti-periplanar to N(i+1) across the CA-C bond,
    # so dihedral N-CA-C-O = psi - 180.
    for i in range(n_res):
        O[i] = nerf(N[i], CA[i], C[i], BL['C-O'], BA['CA-C-O'], psis[i] - 180.0)

    # CB: placed off CA with reference atoms (C, N, CA). Dihedral
    # C-N-CA-CB = -122.6 deg gives a clean L-amino-acid tetrahedral CA.
    for i in range(n_res):
        CB[i] = nerf(C[i], N[i], CA[i], BL['CA-CB'], BA['N-CA-CB'], -122.6)

    return {'N': N, 'CA': CA, 'C': C, 'O': O, 'CB': CB,
            'phi': phis, 'psi': psis, 'omega': omegas}


def write_pdb(filename, atoms, n_res, conf_id=1):
    order = ['N', 'CA', 'C', 'O', 'CB']
    element = {'N': 'N', 'CA': 'C', 'C': 'C', 'O': 'O', 'CB': 'C'}
    serial = 1
    lines = [
        f"REMARK   1 Random poly-alanine conformation #{conf_id}",
         "REMARK   1 Generated by build_idp_conformations.py",
    ]
    for i in range(n_res):
        for name in order:
            x, y, z = atoms[name][i]
            lines.append(
                f"ATOM  {serial:5d}  {name:<3s} ALA A{i+1:4d}    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element[name]:>2s}"
            )
            serial += 1
    lines.append(f"TER   {serial:5d}      ALA A{n_res:4d}")
    lines.append("END")
    with open(filename, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')


def main():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument('--n_aa',    type=int, default=30,
                   help='residues per chain (default: 30)')
    p.add_argument('--n_conf',  type=int, default=10,
                   help='number of PDB files to write (default: 10)')
    p.add_argument('--out_dir', type=str, default='idp_conformations',
                   help='output directory (default: idp_conformations)')
    p.add_argument('--mode', choices=['mixed', 'uniform'], default='mixed',
                   help="phi/psi sampling: 'mixed' (coil basins, default) "
                        "or 'uniform' (uniform Ramachandran)")
    p.add_argument('--seed', type=int, default=None,
                   help='random seed for reproducibility')
    args = p.parse_args()

    if args.seed is not None:
        np.random.seed(args.seed)

    os.makedirs(args.out_dir, exist_ok=True)
    for k in range(args.n_conf):
        atoms = build_chain(args.n_aa, mode=args.mode)
        fn = os.path.join(args.out_dir,
                          f'polyA_{args.n_aa}res_conf{k+1:03d}.pdb')
        write_pdb(fn, atoms, args.n_aa, conf_id=k+1)
        print(f"wrote {fn}")


if __name__ == '__main__':
    main()
    